### ISSUE TITLE
Default path for making the course folder may need to be changed

### ISSUE THREAD

**Issue by neilyml** [sci-oer/student-cli#113]
**Is your feature request related to a problem? Please describe.**

When installing the `scioer student-cli` some Windows 11 users were having issues when the student-cli was trying to create the <course> folder in their Desktop. The issues were mostly related to permission as Windows 11 Desktop folder seems to be very connected to OneDrive (Win 11 may have two Desktop folders - 1 for OneDrive and 1 for local but I am not too sure). For some users, the student-cli was able to create the <course> folder but it was never accessible through their Desktop folder but the user was able to cd into it and find the <course> folder.

**Describe the solution you'd like**

The default path (which is the user's Desktop folder) may need to be changed to fix this. Even the Documents folder may not work as that it also connected to OneDrive

**Describe alternatives you've considered**
 N/A

**Additional context**

Unfortunately, I do not have screenshots today but I will give the student cli a try on a Win 11 machine and post here

**Comment by MarshallAsch** [comment]
Originally we were putting the course content directory into one of the `APPDATA` directory, but decided against continuing to do that because its not the easiest directory to find. 

An alternative thats probably a better first step than changing the default is to add some fallback directories and add a check to make sure the application has write permissions to the data directory. 


Do you have any other paths that are more likely to allow writing _and_ be easily discoverable by the students?

**Comment by neilyml** [comment]
What are your thoughts on putting the course content in the `C:` drive under a folder called 2430? Additionally, once the scioer cli installs successfully, the shell can log out the path where the course content are present too

**Comment by MarshallAsch** [comment]
That isnt really better from a permissions or location perspective. Placing the files at the root of `C:` has the same permissions asking step as the desktop, and is arguably more dangerous from a security perspective because it requires that the application has access to the root. This also would no translate well to linux or to macos. 

The application _does_ allow you to configure the path when you are configuring a new course and you can place the course content anywhere you wish. 

Also now that Im thinking about it the problem your describing is also present if you are using the linux sub system, createing a file on the desktop through that will not put the files on your windows desktop. There isnt currently much we can do about that and it will depend on  the user to correctly specify the path to their desktop or where they want the files to go. 


Im going to mark this as closed because of the pre-existing option to specify the storage location. If you have a solution that can better dynamically select a better path you can open a PR with your proposed ideas and we can try to incorporate that into the tool.
